"""Verify every lab: the buggy code must FAIL its tests and the solution must PASS them.
Run: python tools/check_labs.py   (exit code 1 if any lab is inconsistent; writes docs/LAB_STATUS.md)"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LABS = sorted(p for p in (ROOT / "labs").iterdir() if p.is_dir() and p.name.startswith("lab"))


def run_pytest(lab: Path, src: Path | None) -> tuple[int, str]:
    env = dict(os.environ)
    if src is not None:
        env["ENGDEBUG_LAB_SRC"] = str(src)
    cmd = [
        sys.executable,
        "-m",
        "pytest",
        str(lab),
        "-o",
        "addopts=",
        "-q",
        "--tb=no",
        "-p",
        "no:cacheprovider",
        "--no-header",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env, cwd=ROOT, timeout=900)
    found = re.findall(r"(\d+ (?:passed|failed|error)s?)", proc.stdout)
    return proc.returncode, (", ".join(found) if found else proc.stdout.strip().splitlines()[-1][:50])


def main() -> int:
    rows = []
    ok_all = True
    for lab in LABS:
        number = lab.name[3:5]
        solution = ROOT / "solutions" / f"lab{number}"
        buggy_rc, buggy_summary = run_pytest(lab, None)
        if solution.exists():
            sol_rc, sol_summary = run_pytest(lab, solution)
        else:
            sol_rc, sol_summary = 1, "no solution directory"
        ok = buggy_rc != 0 and sol_rc == 0
        ok_all &= ok
        rows.append(
            (
                lab.name,
                "fails (as intended)" if buggy_rc != 0 else "PASSES (bug missing!)",
                buggy_summary,
                "passes" if sol_rc == 0 else "FAILS",
                sol_summary,
                "ok" if ok else "PROBLEM",
            )
        )
        print(f"{lab.name:<24} buggy: {buggy_summary:<40} solution: {sol_summary:<36} {'ok' if ok else 'PROBLEM'}")
    lines = [
        "# Lab status",
        "",
        "Generated by `python tools/check_labs.py`. Each lab's buggy code must fail its tests and its solution must pass them.",
        "",
        "| lab | buggy code | tests on buggy | solution | tests on solution | status |",
        "|---|---|---|---|---|:-:|",
    ]
    lines += [f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} |" for r in rows]
    (ROOT / "docs" / "LAB_STATUS.md").write_text("\n".join(lines) + "\n")
    print("all labs consistent" if ok_all else "some labs are inconsistent")
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
